package com.mycompany.mercairlineticketing.MERCAirlineTicketing;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Destination extends javax.swing.JFrame {

    //DESIGN IS NOT FINAL
    
    public Destination() {
        super("Himpapawid Airlines Ticketing System");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        pnlDestinationColor1 = new javax.swing.JPanel();
        lblWelcomeText = new javax.swing.JLabel();
        pnlDestinationColor2 = new javax.swing.JPanel();
        pnlLocalInternational = new javax.swing.JPanel();
        rdoLocal = new javax.swing.JRadioButton();
        rdoInternational = new javax.swing.JRadioButton();
        lblFrom = new javax.swing.JLabel();
        cboOrigin = new javax.swing.JComboBox<>();
        lblTo = new javax.swing.JLabel();
        cboDestination = new javax.swing.JComboBox<>();
        rdoOneWay = new javax.swing.JRadioButton();
        rdoRoundTrip = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();

        buttonGroup1.add(rdoLocal);
        buttonGroup1.add(rdoInternational);

        buttonGroup2.add(rdoOneWay);
        buttonGroup2.add(rdoRoundTrip);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        pnlDestinationColor1.setBackground(new java.awt.Color(252, 177, 48));

        lblWelcomeText.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lblWelcomeText.setForeground(new java.awt.Color(29, 72, 134));
        lblWelcomeText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWelcomeText.setText("Welcome to Himpapawid Airlines!");

        javax.swing.GroupLayout pnlDestinationColor1Layout = new javax.swing.GroupLayout(pnlDestinationColor1);
        pnlDestinationColor1.setLayout(pnlDestinationColor1Layout);
        pnlDestinationColor1Layout.setHorizontalGroup(
            pnlDestinationColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDestinationColor1Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(lblWelcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        pnlDestinationColor1Layout.setVerticalGroup(
            pnlDestinationColor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDestinationColor1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblWelcomeText)
                .addGap(28, 28, 28))
        );

        pnlDestinationColor2.setBackground(new java.awt.Color(29, 72, 134));

        pnlLocalInternational.setBackground(new java.awt.Color(252, 177, 48));
        pnlLocalInternational.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        rdoLocal.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        rdoLocal.setForeground(new java.awt.Color(29, 72, 134));
        rdoLocal.setText("Local");
        rdoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoLocalActionPerformed(evt);
            }
        });

        rdoInternational.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        rdoInternational.setForeground(new java.awt.Color(29, 72, 134));
        rdoInternational.setText("International");
        rdoInternational.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoInternationalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLocalInternationalLayout = new javax.swing.GroupLayout(pnlLocalInternational);
        pnlLocalInternational.setLayout(pnlLocalInternationalLayout);
        pnlLocalInternationalLayout.setHorizontalGroup(
            pnlLocalInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocalInternationalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rdoLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(rdoInternational)
                .addGap(20, 20, 20))
        );
        pnlLocalInternationalLayout.setVerticalGroup(
            pnlLocalInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocalInternationalLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlLocalInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoLocal)
                    .addComponent(rdoInternational))
                .addGap(17, 17, 17))
        );

        lblFrom.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblFrom.setForeground(new java.awt.Color(252, 177, 48));
        lblFrom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrom.setText("From:");

        cboOrigin.setBackground(new java.awt.Color(29, 72, 134));
        cboOrigin.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        cboOrigin.setForeground(new java.awt.Color(252, 177, 48));
        cboOrigin.setEnabled(false);
        cboOrigin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOriginItemStateChanged(evt);
            }
        });

        lblTo.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblTo.setForeground(new java.awt.Color(252, 177, 48));
        lblTo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTo.setText("To:");

        cboDestination.setBackground(new java.awt.Color(29, 72, 134));
        cboDestination.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        cboDestination.setForeground(new java.awt.Color(252, 177, 48));
        cboDestination.setEnabled(false);

        rdoOneWay.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        rdoOneWay.setForeground(new java.awt.Color(252, 177, 48));
        rdoOneWay.setText("One-Way");
        rdoOneWay.setEnabled(false);
        rdoOneWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoOneWayActionPerformed(evt);
            }
        });

        rdoRoundTrip.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        rdoRoundTrip.setForeground(new java.awt.Color(252, 177, 48));
        rdoRoundTrip.setText("Round-Trip");
        rdoRoundTrip.setEnabled(false);
        rdoRoundTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoRoundTripActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(252, 177, 48));
        btnNext.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(29, 72, 134));
        btnNext.setText("Next >>");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDestinationColor2Layout = new javax.swing.GroupLayout(pnlDestinationColor2);
        pnlDestinationColor2.setLayout(pnlDestinationColor2Layout);
        pnlDestinationColor2Layout.setHorizontalGroup(
            pnlDestinationColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDestinationColor2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdoOneWay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoRoundTrip)
                .addGap(36, 36, 36)
                .addComponent(btnNext)
                .addGap(156, 156, 156))
            .addGroup(pnlDestinationColor2Layout.createSequentialGroup()
                .addGroup(pnlDestinationColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDestinationColor2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(pnlLocalInternational, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDestinationColor2Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(pnlDestinationColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDestinationColor2Layout.createSequentialGroup()
                                .addComponent(lblFrom)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDestinationColor2Layout.createSequentialGroup()
                                .addComponent(lblTo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlDestinationColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboDestination, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboOrigin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDestinationColor2Layout.setVerticalGroup(
            pnlDestinationColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDestinationColor2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(pnlLocalInternational, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pnlDestinationColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDestinationColor2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cboOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFrom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDestinationColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo))
                .addGap(27, 27, 27)
                .addGroup(pnlDestinationColor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoRoundTrip)
                    .addComponent(btnNext)
                    .addComponent(rdoOneWay))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDestinationColor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDestinationColor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDestinationColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pnlDestinationColor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoLocalActionPerformed
        cboOrigin.setEnabled(true);
        cboOrigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manila", "Batanes", "Palawan" }));
        cboOrigin.setSelectedItem(null);
        cboDestination.setSelectedItem(null);
        
    }//GEN-LAST:event_rdoLocalActionPerformed

    private void rdoInternationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoInternationalActionPerformed
        cboOrigin.setEnabled(true);
        cboOrigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manila", "South Korea", "Japan", "Vietnam" }));
        cboOrigin.setSelectedItem(null);
        cboDestination.setSelectedItem(null);
    }//GEN-LAST:event_rdoInternationalActionPerformed

    private void cboOriginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOriginItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            cboDestination.setEnabled(true);
        
            if(rdoLocal.isSelected() == true){
                if(cboOrigin.getSelectedItem().toString().equals("Manila")) {
                    cboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Batanes", "Palawan" }));
                }
                else if(cboOrigin.getSelectedItem().toString().equals("Batanes") || cboOrigin.getSelectedItem().toString().equals("Palawan")) {
                    cboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manila" }));
                }
            }
        
            else if(rdoInternational.isSelected() == true) {
                if(cboOrigin.getSelectedItem().toString().equals("Manila")) {
                    cboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "South Korea", "Japan", "Vietnam" }));
                }
                else if(cboOrigin.getSelectedItem().toString().equals("South Korea") || cboOrigin.getSelectedItem().toString().equals("Japan") || cboOrigin.getSelectedItem().toString().equals("Vietnam")) {
                    cboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manila" }));
                }
            }
            
            if(cboDestination.getSelectedItem() != null){
                rdoOneWay.setEnabled(true);
                rdoRoundTrip.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cboOriginItemStateChanged

    private void rdoOneWayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoOneWayActionPerformed
        if(rdoLocal.isSelected() == true || rdoInternational.isSelected() == true){
            if(cboOrigin.getSelectedItem() != null && cboDestination.getSelectedItem() != null){
                btnNext.setEnabled(true);
            }
        }
    }//GEN-LAST:event_rdoOneWayActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(cboOrigin.getSelectedItem() == null || cboDestination.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Please select an Origin/Destination before proceeding.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if(cboOrigin.getSelectedItem() != null && cboDestination.getSelectedItem() != null) {
            AirlineType p = new AirlineType();
            p.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void rdoRoundTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoRoundTripActionPerformed
        if(rdoLocal.isSelected() == true || rdoInternational.isSelected() == true){
            if(cboOrigin.getSelectedItem() != null && cboDestination.getSelectedItem() != null){
                btnNext.setEnabled(true);
            }
        }
    }//GEN-LAST:event_rdoRoundTripActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Destination().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JComboBox<String> cboDestination;
    public static javax.swing.JComboBox<String> cboOrigin;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblWelcomeText;
    private javax.swing.JPanel pnlDestinationColor1;
    private javax.swing.JPanel pnlDestinationColor2;
    private javax.swing.JPanel pnlLocalInternational;
    private javax.swing.JRadioButton rdoInternational;
    private javax.swing.JRadioButton rdoLocal;
    public static javax.swing.JRadioButton rdoOneWay;
    protected static javax.swing.JRadioButton rdoRoundTrip;
    // End of variables declaration//GEN-END:variables
}
