package com.mycompany.mercairlineticketing.MERCAirlineTicketing;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Destination extends javax.swing.JFrame {

    /**
     * Creates new form AirlineType
     */
    public Destination() {
        super("MERC Airline System");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblWelcomeText = new javax.swing.JLabel();
        cboOrigin = new javax.swing.JComboBox<>();
        cboDestination = new javax.swing.JComboBox<>();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        rdoOneWay = new javax.swing.JRadioButton();
        rdoRoundTrip = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rdoLocal = new javax.swing.JRadioButton();
        rdoInternational = new javax.swing.JRadioButton();

        buttonGroup1.add(rdoLocal);
        buttonGroup1.add(rdoInternational);

        buttonGroup2.add(rdoOneWay);
        buttonGroup2.add(rdoRoundTrip);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        lblWelcomeText.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblWelcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeText.setText("Welcome to MERC Airline Ticket System!");

        cboOrigin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cboOrigin.setEnabled(false);
        cboOrigin.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboOriginItemStateChanged(evt);
            }
        });
        cboOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboOriginActionPerformed(evt);
            }
        });

        cboDestination.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cboDestination.setEnabled(false);
        cboDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDestinationActionPerformed(evt);
            }
        });

        lblFrom.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblFrom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrom.setText("From:");

        lblTo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblTo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTo.setText("To:");

        rdoOneWay.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rdoOneWay.setText("One-Way");
        rdoOneWay.setEnabled(false);
        rdoOneWay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoOneWayActionPerformed(evt);
            }
        });

        rdoRoundTrip.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rdoRoundTrip.setText("Round-Trip");
        rdoRoundTrip.setEnabled(false);
        rdoRoundTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoRoundTripActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnNext.setText("Next >>");
        btnNext.setEnabled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        rdoLocal.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rdoLocal.setText("Local");
        rdoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoLocalActionPerformed(evt);
            }
        });

        rdoInternational.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        rdoInternational.setText("International");
        rdoInternational.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoInternationalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rdoLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(rdoInternational)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoLocal)
                    .addComponent(rdoInternational))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFrom)
                            .addComponent(lblTo))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(rdoOneWay)
                        .addGap(18, 18, 18)
                        .addComponent(rdoRoundTrip)
                        .addGap(49, 49, 49)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblWelcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblWelcomeText)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(cboOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoOneWay)
                    .addComponent(rdoRoundTrip)
                    .addComponent(btnNext))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboOriginActionPerformed
        
    }//GEN-LAST:event_cboOriginActionPerformed

    private void rdoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoLocalActionPerformed
        cboOrigin.setEnabled(true);
        cboOrigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manila", "Batanes", "Palawan" }));
        cboOrigin.setSelectedItem(null);
        cboDestination.setSelectedItem(null);
        
    }//GEN-LAST:event_rdoLocalActionPerformed

    private void rdoInternationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoInternationalActionPerformed
        cboOrigin.setEnabled(true);
        cboOrigin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manila", "South Korea", "Japan", "Vietnam" }));
        cboOrigin.setSelectedItem(null);
        cboDestination.setSelectedItem(null);
    }//GEN-LAST:event_rdoInternationalActionPerformed

    private void cboOriginItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboOriginItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            cboDestination.setEnabled(true);
        
            if(rdoLocal.isSelected() == true){
                if(cboOrigin.getSelectedItem().toString().equals("Manila")) {
                    cboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Batanes", "Palawan" }));
                }
                else if(cboOrigin.getSelectedItem().toString().equals("Batanes") || cboOrigin.getSelectedItem().toString().equals("Palawan")) {
                    cboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manila" }));
                }
            }
        
            else if(rdoInternational.isSelected() == true) {
                if(cboOrigin.getSelectedItem().toString().equals("Manila")) {
                    cboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "South Korea", "Japan", "Vietnam" }));
                }
                else if(cboOrigin.getSelectedItem().toString().equals("South Korea") || cboOrigin.getSelectedItem().toString().equals("Japan") || cboOrigin.getSelectedItem().toString().equals("Vietnam")) {
                    cboDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manila" }));
                }
            }
            
            if(cboDestination.getSelectedItem() != null){
                rdoOneWay.setEnabled(true);
                rdoRoundTrip.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cboOriginItemStateChanged

    private void cboDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDestinationActionPerformed

    private void rdoOneWayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoOneWayActionPerformed
        if(rdoLocal.isSelected() == true || rdoInternational.isSelected() == true){
            if(cboOrigin.getSelectedItem() != null && cboDestination.getSelectedItem() != null){
                btnNext.setEnabled(true);
            }
        }
    }//GEN-LAST:event_rdoOneWayActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if(cboOrigin.getSelectedItem() == null || cboDestination.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Please select an Origin/Destination before proceeding.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if(cboOrigin.getSelectedItem() != null && cboDestination.getSelectedItem() != null) {
            AirlineType p = new AirlineType();
            p.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void rdoRoundTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoRoundTripActionPerformed
        if(rdoLocal.isSelected() == true || rdoInternational.isSelected() == true){
            if(cboOrigin.getSelectedItem() != null && cboDestination.getSelectedItem() != null){
                btnNext.setEnabled(true);
            }
        }
    }//GEN-LAST:event_rdoRoundTripActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Destination().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JComboBox<String> cboDestination;
    public static javax.swing.JComboBox<String> cboOrigin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblWelcomeText;
    private javax.swing.JRadioButton rdoInternational;
    private javax.swing.JRadioButton rdoLocal;
    public static javax.swing.JRadioButton rdoOneWay;
    protected static javax.swing.JRadioButton rdoRoundTrip;
    // End of variables declaration//GEN-END:variables
}
