package com.iaapdevgroup2.mercairlineticketing;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class AirlineType extends javax.swing.JFrame {

    /**
     * Creates new form Passengers
     */
    public AirlineType() {
        super("Himpapawid Airlines Ticketing System");
        initComponents();
        this.setLocationRelativeTo(null);
    }
    private int maxSeat=0;
    protected static int passengerCount=0;
    protected static int minorCount;
    protected static int adultCount;
    protected static int seniorCount;
    
    public String getPassengerCount(){
        
        String passengerNumber = Integer.toString(passengerCount);
        return passengerNumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAirlineType = new javax.swing.JLabel();
        cboAirlineType = new javax.swing.JComboBox<>();
        btnProceed = new javax.swing.JButton();
        pnlPassengerType = new javax.swing.JPanel();
        cboAdultCount = new javax.swing.JComboBox<>();
        lblAdults = new javax.swing.JLabel();
        cboSeniorsCount = new javax.swing.JComboBox<>();
        lblSeniors = new javax.swing.JLabel();
        cboMinorsCount = new javax.swing.JComboBox<>();
        lblMinors = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Airline Type");

        lblAirlineType.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblAirlineType.setText("Choose an Airline Type:");

        cboAirlineType.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cboAirlineType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Business", "Private" }));
        cboAirlineType.setSelectedItem(null);
        cboAirlineType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboAirlineTypeItemStateChanged(evt);
            }
        });
        cboAirlineType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAirlineTypeActionPerformed(evt);
            }
        });

        btnProceed.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnProceed.setText("Proceed >>");
        btnProceed.setEnabled(false);
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        pnlPassengerType.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "How many seats do you want to reserve?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 14))); // NOI18N

        cboAdultCount.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cboAdultCount.setSelectedItem(null);
        cboAdultCount.setEnabled(false);

        lblAdults.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        lblAdults.setText("Adults (18-59)");

        cboSeniorsCount.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cboSeniorsCount.setSelectedItem(null);
        cboSeniorsCount.setEnabled(false);

        lblSeniors.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        lblSeniors.setText("Seniors (60+)");

        cboMinorsCount.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cboMinorsCount.setSelectedItem(null);
        cboMinorsCount.setEnabled(false);

        lblMinors.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        lblMinors.setText("Minors (0-17)");

        javax.swing.GroupLayout pnlPassengerTypeLayout = new javax.swing.GroupLayout(pnlPassengerType);
        pnlPassengerType.setLayout(pnlPassengerTypeLayout);
        pnlPassengerTypeLayout.setHorizontalGroup(
            pnlPassengerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassengerTypeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlPassengerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboAdultCount, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPassengerTypeLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblAdults)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pnlPassengerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassengerTypeLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSeniors))
                    .addComponent(cboSeniorsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlPassengerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassengerTypeLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblMinors))
                    .addComponent(cboMinorsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        pnlPassengerTypeLayout.setVerticalGroup(
            pnlPassengerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassengerTypeLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlPassengerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassengerTypeLayout.createSequentialGroup()
                        .addComponent(cboAdultCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdults))
                    .addGroup(pnlPassengerTypeLayout.createSequentialGroup()
                        .addGroup(pnlPassengerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboMinorsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSeniorsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPassengerTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMinors)
                            .addComponent(lblSeniors))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(btnProceed))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAirlineType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboAirlineType, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pnlPassengerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAirlineType)
                    .addComponent(cboAirlineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(pnlPassengerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        minorCount = Integer.parseInt(cboMinorsCount.getSelectedItem().toString());
        adultCount = Integer.parseInt(cboAdultCount.getSelectedItem().toString());
        seniorCount = Integer.parseInt(cboSeniorsCount.getSelectedItem().toString());
        
        Boolean confirmation = false;
        passengerCount = Integer.parseInt(cboAdultCount.getSelectedItem().toString()) + Integer.parseInt(cboMinorsCount.getSelectedItem().toString()) + Integer.parseInt(cboSeniorsCount.getSelectedItem().toString());
        
        if(passengerCount > maxSeat)
            JOptionPane.showMessageDialog(null, "The total reservation count must not exceed " + maxSeat + ".", "Error", JOptionPane.ERROR_MESSAGE);
        else if(passengerCount < 1)
            JOptionPane.showMessageDialog(null, "The total reservation count must not be 0.", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            if((Integer.parseInt(cboAdultCount.getSelectedItem().toString()) + Integer.parseInt(cboSeniorsCount.getSelectedItem().toString())) == 0)
                JOptionPane.showMessageDialog(null, "Minors are not allowed to reserve a seat without an adult(18 and above).", "Error", JOptionPane.ERROR_MESSAGE);
            else
                confirmation = true;
        }
        
        if(confirmation == true){
            Passengers p = new Passengers();
            p.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnProceedActionPerformed

    private void cboAirlineTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAirlineTypeActionPerformed
        cboAdultCount.setEnabled(true);
        cboMinorsCount.setEnabled(true);
        cboSeniorsCount.setEnabled(true);
        btnProceed.setEnabled(true);
    }//GEN-LAST:event_cboAirlineTypeActionPerformed

    private void cboAirlineTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboAirlineTypeItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            if(cboAirlineType.getSelectedItem().toString().equals("Private")){
                maxSeat = 14;
            }
            else if(cboAirlineType.getSelectedItem().toString().equals("Business")){
                maxSeat = 23;
            }
            else if (cboAirlineType.getSelectedItem().toString().equals("Regular")){
                maxSeat = 48;
            }
            
            String[] passengerSeat = new String[maxSeat + 1];
        
            for(int a = 0; a < passengerSeat.length; a++){
                passengerSeat[a] = String.valueOf(a);
            }
            cboAdultCount.setModel(new javax.swing.DefaultComboBoxModel<>(passengerSeat));
            cboMinorsCount.setModel(new javax.swing.DefaultComboBoxModel<>(passengerSeat));
            cboSeniorsCount.setModel(new javax.swing.DefaultComboBoxModel<>(passengerSeat));
            
            cboAdultCount.setSelectedItem(passengerSeat[0]);
            cboMinorsCount.setSelectedItem(passengerSeat[0]);
            cboSeniorsCount.setSelectedItem(passengerSeat[0]);
        }
    }//GEN-LAST:event_cboAirlineTypeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirlineType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirlineType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirlineType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirlineType.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirlineType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProceed;
    private javax.swing.JComboBox<String> cboAdultCount;
    public static javax.swing.JComboBox<String> cboAirlineType;
    private javax.swing.JComboBox<String> cboMinorsCount;
    private javax.swing.JComboBox<String> cboSeniorsCount;
    private javax.swing.JLabel lblAdults;
    private javax.swing.JLabel lblAirlineType;
    private javax.swing.JLabel lblMinors;
    private javax.swing.JLabel lblSeniors;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlPassengerType;
    // End of variables declaration//GEN-END:variables
}
