package com.iaapdevgroup2.mercairlineticketing;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.time.LocalDate;
import java.time.Period;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Passengers extends javax.swing.JFrame {

    private static int day;
    private static int month;
    private static int year;
    private final String[] YEAR_CHOICES = new String[117];
    private int days = 0;
    private int period = 0;
    protected static String oneWayRoundTrip;
    static DefaultTableModel table = new DefaultTableModel();
    private String insurance;
    protected static int insuranceCounter;
    private String passenger;
    private int minorCounter = 0;
    private int adultCounter = 0;
    private int seniorCounter = 0;
    private int passengerCounter = 0;
    private boolean validation;
    private int passengerAge;
    
    private boolean minor;
    private boolean adult;
    private boolean senior;
    
    Color sgBlue = new Color(29,72,134);;
    
    public Passengers() {
        super("Himpapawid Airlines Ticketing System");
        initComponents();
        
        ImageIcon himpapawidTopIcon = new ImageIcon(getClass().getResource("/images/LogoWName.png"));
        setIconImage(himpapawidTopIcon.getImage());
        
        Icon icon = lblLogo.getIcon();
        ImageIcon airlineLogo = (ImageIcon)icon;
        Image image = airlineLogo.getImage().getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH);
        lblLogo.setIcon(new ImageIcon (image));
        
        table = (DefaultTableModel) tblPassengerData.getModel();
        JTableHeader header = tblPassengerData.getTableHeader();

        header.setForeground(sgBlue);
        header.setFont(new Font("SansSerif", 3, 18));
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insuranceGroup = new javax.swing.ButtonGroup();
        pnlPassengerTopBar = new javax.swing.JPanel();
        lblAirlineTypeTitle = new javax.swing.JLabel();
        lblTagline = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlPassengerBackground = new javax.swing.JPanel();
        lblNoPassengers = new javax.swing.JLabel();
        lblFlight = new javax.swing.JLabel();
        txtFlight = new javax.swing.JTextField();
        txtPassengers = new javax.swing.JTextField();
        lblAirlineType = new javax.swing.JLabel();
        txtAirlineType = new javax.swing.JTextField();
        txtOneWayRoundTrip = new javax.swing.JTextField();
        lblPassengerTitle = new javax.swing.JLabel();
        pnlPassengerInput = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        pnlnsurance = new javax.swing.JPanel();
        rdoYes = new javax.swing.JRadioButton();
        rdoNo = new javax.swing.JRadioButton();
        lblBirthday = new javax.swing.JLabel();
        lblYYYY = new javax.swing.JLabel();
        cboYYYY = new javax.swing.JComboBox<>();
        lblSlash1 = new javax.swing.JLabel();
        cboMM = new javax.swing.JComboBox<>();
        lblMM = new javax.swing.JLabel();
        lblSlash2 = new javax.swing.JLabel();
        cboDD = new javax.swing.JComboBox<>();
        lblDD = new javax.swing.JLabel();
        pnlPassengerInputTopBar = new javax.swing.JPanel();
        lblPanelText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPassengerData = new javax.swing.JTable();
        btnProceed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(29, 72, 134));

        pnlPassengerTopBar.setBackground(new java.awt.Color(252, 177, 48));

        lblAirlineTypeTitle.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        lblAirlineTypeTitle.setForeground(new java.awt.Color(29, 72, 134));
        lblAirlineTypeTitle.setText("Himpapawid Airlines");

        lblTagline.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblTagline.setForeground(new java.awt.Color(29, 72, 134));
        lblTagline.setText("Taking care to the new heights");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoWName.png")));

        javax.swing.GroupLayout pnlPassengerTopBarLayout = new javax.swing.GroupLayout(pnlPassengerTopBar);
        pnlPassengerTopBar.setLayout(pnlPassengerTopBarLayout);
        pnlPassengerTopBarLayout.setHorizontalGroup(
            pnlPassengerTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassengerTopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPassengerTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTagline)
                    .addComponent(lblAirlineTypeTitle))
                .addGap(18, 18, 18)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        pnlPassengerTopBarLayout.setVerticalGroup(
            pnlPassengerTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassengerTopBarLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(pnlPassengerTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassengerTopBarLayout.createSequentialGroup()
                        .addComponent(lblAirlineTypeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTagline))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlPassengerBackground.setBackground(new java.awt.Color(29, 72, 134));

        lblNoPassengers.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblNoPassengers.setForeground(new java.awt.Color(252, 177, 48));
        lblNoPassengers.setText("Number of Passengers:");

        lblFlight.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblFlight.setForeground(new java.awt.Color(252, 177, 48));
        lblFlight.setText("Chosen Flight:");

        txtFlight.setBackground(new java.awt.Color(29, 72, 134));
        txtFlight.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        txtFlight.setForeground(new java.awt.Color(252, 177, 48));
        txtFlight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFlight.setText(String.valueOf(Destination.cboOrigin.getSelectedItem()) + " to " + String.valueOf(Destination.cboDestination.getSelectedItem()));
        txtFlight.setEnabled(false);

        txtPassengers.setBackground(new java.awt.Color(29, 72, 134));
        txtPassengers.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        txtPassengers.setForeground(new java.awt.Color(252, 177, 48));
        txtPassengers.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPassengers.setText(String.valueOf(AirlineType.passengerCount));
        txtPassengers.setEnabled(false);

        lblAirlineType.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblAirlineType.setForeground(new java.awt.Color(252, 177, 48));
        lblAirlineType.setText("Chosen Airline Type:");

        txtAirlineType.setBackground(new java.awt.Color(29, 72, 134));
        txtAirlineType.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        txtAirlineType.setForeground(new java.awt.Color(252, 177, 48));
        txtAirlineType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAirlineType.setText(String.valueOf(AirlineType.cboAirlineType.getSelectedItem()));
        txtAirlineType.setEnabled(false);

        txtOneWayRoundTrip.setBackground(new java.awt.Color(29, 72, 134));
        txtOneWayRoundTrip.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        if(Destination.cboOneWayRoundTrip.getSelectedItem().equals("One-Way")){
            oneWayRoundTrip = "One-Way";
        }
        else if(Destination.cboOneWayRoundTrip.getSelectedItem().equals("Round-Trip")){
            oneWayRoundTrip = "Round-Trip";
        }
        txtOneWayRoundTrip.setForeground(new java.awt.Color(252, 177, 48));
        txtOneWayRoundTrip.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOneWayRoundTrip.setText(oneWayRoundTrip);
        txtOneWayRoundTrip.setEnabled(false);

        lblPassengerTitle.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        lblPassengerTitle.setForeground(new java.awt.Color(252, 177, 48));
        lblPassengerTitle.setText("Passenger Information");

        pnlPassengerInput.setBackground(new java.awt.Color(29, 72, 134));
        pnlPassengerInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48), 3));

        lblName.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(252, 177, 48));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblName.setText("Name:");

        txtName.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnAdd.setBackground(new java.awt.Color(252, 177, 48));
        btnAdd.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(29, 72, 134));
        btnAdd.setText("Add >>");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblAge.setForeground(new java.awt.Color(252, 177, 48));
        lblAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAge.setText("Age:");

        txtAge.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtAge.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAge.setEnabled(false);

        pnlnsurance.setBackground(new java.awt.Color(29, 72, 134));
        pnlnsurance.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 177, 48)), "Insurance?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 3, 18), new java.awt.Color(252, 177, 48))); // NOI18N

        insuranceGroup.add(rdoYes);
        rdoYes.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        rdoYes.setForeground(new java.awt.Color(252, 177, 48));
        rdoYes.setText("Yes");

        insuranceGroup.add(rdoNo);
        rdoNo.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        rdoNo.setForeground(new java.awt.Color(252, 177, 48));
        rdoNo.setText("No");

        javax.swing.GroupLayout pnlnsuranceLayout = new javax.swing.GroupLayout(pnlnsurance);
        pnlnsurance.setLayout(pnlnsuranceLayout);
        pnlnsuranceLayout.setHorizontalGroup(
            pnlnsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlnsuranceLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rdoYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(rdoNo)
                .addGap(28, 28, 28))
        );
        pnlnsuranceLayout.setVerticalGroup(
            pnlnsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlnsuranceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlnsuranceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoYes)
                    .addComponent(rdoNo))
                .addContainerGap())
        );

        lblBirthday.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblBirthday.setForeground(new java.awt.Color(252, 177, 48));
        lblBirthday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBirthday.setText("Birthday:");

        lblYYYY.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblYYYY.setForeground(new java.awt.Color(252, 177, 48));
        lblYYYY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYYYY.setText("YYYY");
        lblYYYY.setToolTipText("");

        cboYYYY.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        for(int b = 0; b < YEAR_CHOICES.length; b++){
            YEAR_CHOICES[b] = String.valueOf(2023 - b);
        }
        cboYYYY.setModel(new javax.swing.DefaultComboBoxModel<>(YEAR_CHOICES));
        cboYYYY.setSelectedItem(null);
        cboYYYY.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboYYYYItemStateChanged(evt);
            }
        });

        lblSlash1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblSlash1.setForeground(new java.awt.Color(252, 177, 48));
        lblSlash1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlash1.setText("/");

        cboMM.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cboMM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cboMM.setSelectedItem(null);
        cboMM.setEnabled(false);
        cboMM.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMMItemStateChanged(evt);
            }
        });

        lblMM.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblMM.setForeground(new java.awt.Color(252, 177, 48));
        lblMM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMM.setText("MM");
        lblMM.setToolTipText("");

        lblSlash2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblSlash2.setForeground(new java.awt.Color(252, 177, 48));
        lblSlash2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSlash2.setText("/");

        cboDD.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cboDD.setSelectedItem(null);
        cboDD.setEnabled(false);
        cboDD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDDItemStateChanged(evt);
            }
        });

        lblDD.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDD.setForeground(new java.awt.Color(252, 177, 48));
        lblDD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDD.setText("DD");
        lblDD.setToolTipText("");

        pnlPassengerInputTopBar.setBackground(new java.awt.Color(252, 177, 48));

        lblPanelText.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblPanelText.setForeground(new java.awt.Color(29, 72, 134));
        lblPanelText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passengerTitleMethod();

        javax.swing.GroupLayout pnlPassengerInputTopBarLayout = new javax.swing.GroupLayout(pnlPassengerInputTopBar);
        pnlPassengerInputTopBar.setLayout(pnlPassengerInputTopBarLayout);
        pnlPassengerInputTopBarLayout.setHorizontalGroup(
            pnlPassengerInputTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassengerInputTopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPanelText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPassengerInputTopBarLayout.setVerticalGroup(
            pnlPassengerInputTopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassengerInputTopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPanelText)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPassengerInputLayout = new javax.swing.GroupLayout(pnlPassengerInput);
        pnlPassengerInput.setLayout(pnlPassengerInputLayout);
        pnlPassengerInputLayout.setHorizontalGroup(
            pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName))
                    .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                        .addComponent(lblBirthday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                                .addComponent(cboYYYY, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassengerInputLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblYYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addComponent(lblSlash1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblMM))
                            .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                                .addComponent(cboMM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSlash2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboDD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblDD)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassengerInputLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlnsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addContainerGap())
            .addComponent(pnlPassengerInputTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPassengerInputLayout.setVerticalGroup(
            pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassengerInputLayout.createSequentialGroup()
                .addComponent(pnlPassengerInputTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                            .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboYYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSlash1)
                                .addComponent(lblBirthday))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblYYYY))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassengerInputLayout.createSequentialGroup()
                            .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSlash2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblMM)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassengerInputLayout.createSequentialGroup()
                        .addComponent(cboDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDD)))
                .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPassengerInputLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnlPassengerInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83))
                    .addGroup(pnlPassengerInputLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(pnlnsurance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addContainerGap())))
        );

        tblPassengerData.setBackground(new java.awt.Color(29, 72, 134));
        tblPassengerData.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        tblPassengerData.setForeground(new java.awt.Color(252, 177, 48));
        tblPassengerData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Insurance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPassengerData);

        btnProceed.setBackground(new java.awt.Color(252, 177, 48));
        btnProceed.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        btnProceed.setForeground(new java.awt.Color(29, 72, 134));
        btnProceed.setText("Proceed >>");
        btnProceed.setEnabled(false);
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPassengerBackgroundLayout = new javax.swing.GroupLayout(pnlPassengerBackground);
        pnlPassengerBackground.setLayout(pnlPassengerBackgroundLayout);
        pnlPassengerBackgroundLayout.setHorizontalGroup(
            pnlPassengerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassengerBackgroundLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlPassengerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassengerBackgroundLayout.createSequentialGroup()
                        .addComponent(lblNoPassengers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPassengerTitle)
                    .addGroup(pnlPassengerBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlPassengerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlPassengerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPassengerBackgroundLayout.createSequentialGroup()
                                .addComponent(lblFlight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlPassengerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPassengerBackgroundLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlPassengerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPassengerBackgroundLayout.createSequentialGroup()
                                        .addComponent(lblAirlineType)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAirlineType, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtOneWayRoundTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlPassengerBackgroundLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(btnProceed)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        pnlPassengerBackgroundLayout.setVerticalGroup(
            pnlPassengerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassengerBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPassengerTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlPassengerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoPassengers)
                    .addComponent(txtPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAirlineType)
                    .addComponent(txtAirlineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOneWayRoundTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPassengerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlight)
                    .addComponent(txtFlight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPassengerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassengerBackgroundLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnProceed))
                    .addComponent(pnlPassengerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPassengerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlPassengerTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(pnlPassengerBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlPassengerTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(txtName.getText().trim().isEmpty() == false && txtAge.getText().trim().isEmpty() == false && insuranceGroup.getSelection() != null){
            if(table.getRowCount()+1 <= AirlineType.passengerCount){
                minor = false;
                adult = false;
                senior = false;
                
                insurance = "";
        
                if(rdoYes.isSelected()){
                    insurance = rdoYes.getText();
                }
                else if(rdoNo.isSelected()){
                    insurance = rdoNo.getText();
                }
                
                validation = false;
                passengerTitleMethod();
                
                passengerAge = Integer.parseInt(txtAge.getText());
                if(minorCounter < AirlineType.minorCount && AirlineType.minorCount != 0){
                    if(passengerAge >= 0 && passengerAge <= 17){
                        minor = true;
                        validation = true;
                    }
                }
                else if(adultCounter < AirlineType.adultCount && AirlineType.adultCount != 0){
                    if(passengerAge >= 18 && passengerAge <= 59){
                        adult = true;
                        validation = true;
                    }
                }
                else if(seniorCounter < AirlineType.seniorCount && AirlineType.seniorCount != 0){
                    if(passengerAge >= 60){
                        senior = true;
                        validation = true;
                    }
                }
                        
                if(validation == true){
                    table.insertRow(table.getRowCount(), new Object[]{txtName.getText(), txtAge.getText(), insurance});
                    txtName.setText("");
                    txtAge.setText("");
                    cboMM.setSelectedItem(null);
                    cboDD.setSelectedItem(null);
                    cboYYYY.setSelectedItem(null);
                    
                    if(rdoYes.isSelected()){
                        insuranceCounter++;
                    }
                    insuranceGroup.clearSelection();
                    
                    if(minor == true){
                        minorCounter++;
                    }
                    else if(adult == true){
                        adultCounter++;
                    }
                    else if(senior == true){
                        seniorCounter++;
                    }
                }
                else{
                    passengerCounter--;
                    JOptionPane.showMessageDialog(null, "Enter a valid age for the specific age range of the passenger.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                if(table.getRowCount() == AirlineType.passengerCount){
                    btnProceed.setEnabled(true);
                    txtName.setEditable(false);
                    cboMM.setEnabled(false);
                    cboDD.setEnabled(false);
                    cboYYYY.setEnabled(false);
                    rdoYes.setEnabled(false);
                    rdoNo.setEnabled(false);
                    btnAdd.setEnabled(false);
                    lblPanelText.setText("(CLICK PROCEED BUTTON)");
                }
            }
        }
        else if(txtName.getText().trim().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Please enter your name before proceeding.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(txtAge.getText().trim().isEmpty() == true){
            JOptionPane.showMessageDialog(null, "Please fill in the date of birth of passenger before proceeding.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if(insuranceGroup.getSelection() == null){
            JOptionPane.showMessageDialog(null, "Please enter whether you want an insurance or not before proceeding.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        Transaction t = new Transaction();
        t.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProceedActionPerformed

    private void cboMMItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMMItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            String selectedMonth = cboMM.getSelectedItem().toString();
    
            if(Integer.parseInt(selectedMonth) == 1 || Integer.parseInt(selectedMonth) == 3 || Integer.parseInt(selectedMonth) == 5 || Integer.parseInt(selectedMonth) == 7 || Integer.parseInt(selectedMonth) == 8 || Integer.parseInt(selectedMonth) == 10 || Integer.parseInt(selectedMonth) == 12){
                days = 31;
            }
            else if(Integer.parseInt(cboMM.getSelectedItem().toString()) == 2){
                days = 29;
            }
            else{
                days = 30;
            }
        
            String dayChoices[] = new String[days];
        
            for(int c = 0; c < dayChoices.length;c++){
                if(c < 9){
                    dayChoices[c] = "0" + String.valueOf(c+1); 
                }
                else{
                    dayChoices[c] = String.valueOf(c+1); 
                }
            }
        
            cboDD.setModel(new javax.swing.DefaultComboBoxModel<>(dayChoices));
            cboDD.setSelectedItem(null);
            
            if(cboMM.getSelectedItem() != null){
                cboDD.setEnabled(true);
            }
        
            if(cboDD.getSelectedItem() != null && cboMM.getSelectedItem() != null && cboYYYY.getSelectedItem() != null){
                year = Integer.parseInt(cboYYYY.getSelectedItem().toString());
                month = Integer.parseInt(cboMM.getSelectedItem().toString());
                day = Integer.parseInt(cboDD.getSelectedItem().toString());
        
                LocalDate bday = LocalDate.of(year,month,day);
                LocalDate currentDate = LocalDate.now();
                year = bday.getYear();
                month = bday.getMonthValue();
                day = bday.getDayOfMonth();
        
                period = Period.between(bday, currentDate).getYears();
        
                txtAge.setText(String.valueOf(period));
            }
        }
    }//GEN-LAST:event_cboMMItemStateChanged

    private void cboYYYYItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboYYYYItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            
            if(cboYYYY != null){
                cboMM.setEnabled(true);
            }
            
            if(cboDD.getSelectedItem() != null && cboMM.getSelectedItem() != null && cboYYYY.getSelectedItem() != null){
                year = Integer.parseInt(cboYYYY.getSelectedItem().toString());
                month = Integer.parseInt(cboMM.getSelectedItem().toString());
                day = Integer.parseInt(cboDD.getSelectedItem().toString());
        
                LocalDate bday = LocalDate.of(year,month,day);
                LocalDate currentDate = LocalDate.now();
                year = bday.getYear();
                month = bday.getMonthValue();
                day = bday.getDayOfMonth();
        
                period = Period.between(bday, currentDate).getYears();
        
                txtAge.setText(String.valueOf(period));
            }
        }
    }//GEN-LAST:event_cboYYYYItemStateChanged

    private void cboDDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDDItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            if(cboDD.getSelectedItem() != null && cboMM.getSelectedItem() != null && cboYYYY.getSelectedItem() != null){
                year = Integer.parseInt(cboYYYY.getSelectedItem().toString());
                month = Integer.parseInt(cboMM.getSelectedItem().toString());
                day = Integer.parseInt(cboDD.getSelectedItem().toString());
        
                LocalDate bday = LocalDate.of(year,month,day);
                LocalDate currentDate = LocalDate.now();
                year = bday.getYear();
                month = bday.getMonthValue();
                day = bday.getDayOfMonth();
        
                period = Period.between(bday, currentDate).getYears();
        
                txtAge.setText(String.valueOf(period));
            }
        }
    }//GEN-LAST:event_cboDDItemStateChanged
    
    private void passengerTitleMethod(){
        passengerCounter++;
                
        if(minorCounter < AirlineType.minorCount && AirlineType.minorCount != 0){
            lblPanelText.setText("Passenger " + Integer.toString(passengerCounter) + ": (Minor)");
        }
        else if(adultCounter < AirlineType.adultCount && AirlineType.adultCount != 0){
            lblPanelText.setText("Passenger " + Integer.toString(passengerCounter) + ": (Adult)");
        }
        else if(seniorCounter < AirlineType.seniorCount && AirlineType.seniorCount != 0){
            lblPanelText.setText("Passenger " + Integer.toString(passengerCounter) + ": (Senior)");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passengers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnProceed;
    private javax.swing.JComboBox<String> cboDD;
    private javax.swing.JComboBox<String> cboMM;
    private javax.swing.JComboBox<String> cboYYYY;
    private javax.swing.ButtonGroup insuranceGroup;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAirlineType;
    private javax.swing.JLabel lblAirlineTypeTitle;
    private javax.swing.JLabel lblBirthday;
    private javax.swing.JLabel lblDD;
    private javax.swing.JLabel lblFlight;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMM;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNoPassengers;
    private javax.swing.JLabel lblPanelText;
    private javax.swing.JLabel lblPassengerTitle;
    private javax.swing.JLabel lblSlash1;
    private javax.swing.JLabel lblSlash2;
    private javax.swing.JLabel lblTagline;
    private javax.swing.JLabel lblYYYY;
    private javax.swing.JPanel pnlPassengerBackground;
    private javax.swing.JPanel pnlPassengerInput;
    private javax.swing.JPanel pnlPassengerInputTopBar;
    private javax.swing.JPanel pnlPassengerTopBar;
    private javax.swing.JPanel pnlnsurance;
    private javax.swing.JRadioButton rdoNo;
    private javax.swing.JRadioButton rdoYes;
    protected static javax.swing.JTable tblPassengerData;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAirlineType;
    protected static javax.swing.JTextField txtFlight;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOneWayRoundTrip;
    private javax.swing.JTextField txtPassengers;
    // End of variables declaration//GEN-END:variables
}
