/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iaapdevgroup2.mercairlineticketing;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class PriceBreakdown extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    private static int passengerCount = AirlineType.passengerCount;
    protected String passengerType;
    private static double price = 0;
    private static double baggagePrice = 0;
    private static double insurancePrice = 0;
    private static double taxFee = 0;
    
    public PriceBreakdown() {
        super("Himpapawid Airlines Ticketing System");
        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) tblPassengerBreakdown.getModel();
        TableData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPassengerBreakdown = new javax.swing.JTable();
        btnConfirmAndExit = new javax.swing.JButton();
        lblPriceBreakdown = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPassengerBreakdown.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        tblPassengerBreakdown.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Price", "Baggage", "Insurance", "Tax"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPassengerBreakdown);

        btnConfirmAndExit.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btnConfirmAndExit.setText(">>CONFIRM AND EXIT<<");
        btnConfirmAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmAndExitActionPerformed(evt);
            }
        });

        lblPriceBreakdown.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblPriceBreakdown.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceBreakdown.setText("PRICE BREAKDOWN");

        lblNote.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblNote.setText("*Please take note of the Transaction fee present on the \"Payment Summary\" tab.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(btnConfirmAndExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(lblPriceBreakdown))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblNote)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(lblPriceBreakdown)
                .addGap(4, 4, 4)
                .addComponent(lblNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmAndExit)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmAndExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnConfirmAndExitActionPerformed

    private void TableData(){
        int nameColumnIndex = 0;
        int ageColumnIndex = 1;
        int insuranceColumnIndex = 2;
        
        for(int a = 0;a < passengerCount;a++){
            Object passengerNames = Passengers.table.getValueAt(a, nameColumnIndex);
            Object passengerAges = Passengers.table.getValueAt(a, ageColumnIndex);
            Object passengerInsurances = Passengers.table.getValueAt(a, insuranceColumnIndex);
            
            if(Integer.parseInt(passengerAges.toString()) > 0 && Integer.parseInt(passengerAges.toString()) < 18){
                passengerType = "MINOR";
            }
            else if(Integer.parseInt(passengerAges.toString()) > 17 && Integer.parseInt(passengerAges.toString()) < 60){
                passengerType = "ADULT";
            }
            else{
                passengerType = "SENIOR";
            }
            
            price = Transaction.initialPrice;
            
            
            if(passengerInsurances.equals("Yes")){
                insurancePrice = Transaction.initialInsurance;
            }
            else if(passengerInsurances.equals("No")){
                insurancePrice = 0;
            }
            
            taxFee = Transaction.taxFee / Double.valueOf(AirlineType.passengerCount - AirlineType.seniorCount);
            
            if(Integer.parseInt(passengerAges.toString()) >= 60){
                price = price - (price * 0.2);
                taxFee = 0;
            }
            
            baggagePrice = Transaction.baggageTotal / passengerCount;
            System.out.println("passengerInsurances: " + passengerInsurances);

            model.addRow(new Object[]{passengerNames, passengerType, price, baggagePrice, insurancePrice, taxFee});
    	}
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PriceBreakdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PriceBreakdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PriceBreakdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PriceBreakdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PriceBreakdown().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmAndExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPriceBreakdown;
    private static javax.swing.JTable tblPassengerBreakdown;
    // End of variables declaration//GEN-END:variables
}
