/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iaapdevgroup2.mercairlineticketing;

import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class Receipt extends javax.swing.JFrame {

    LocalDate currentDate = LocalDate.now();
    DateTimeFormatter dateFormatted = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    private final String CURRENT_DATE_FORMATTED = currentDate.format(dateFormatted);
    private int flightOneDay;
    private int flightOneMonth;
    private int flightOneYear;
    private int flightTwoDay;
    private int flightTwoMonth;
    private int flightTwoYear;
    private String flightOne;
    private String flightTwo;
    
    public Receipt() {
        super("Himpapawid Airlines Ticketing System");
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(654, 950);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlReceiptBackground = new javax.swing.JPanel();
        lblTransactionNumber = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        pnlFlightOne = new javax.swing.JPanel();
        pnlFlighOneBar = new javax.swing.JPanel();
        lblFlightOne = new javax.swing.JLabel();
        lblFlightOneDepart = new javax.swing.JLabel();
        lblFlightOneArrive = new javax.swing.JLabel();
        lblReceiptAirlineTypeOne = new javax.swing.JLabel();
        lblDateofDepartureOne = new javax.swing.JLabel();
        lblDepartLocationOne = new javax.swing.JLabel();
        lblArriveLocationOne = new javax.swing.JLabel();
        lblDepartureDate = new javax.swing.JLabel();
        lblAirlineTypeFlightOne = new javax.swing.JLabel();
        pnlFlightTwo = new javax.swing.JPanel();
        pnlFlightTwoBar = new javax.swing.JPanel();
        lblFlightTwo = new javax.swing.JLabel();
        lblFlightTwoDepart = new javax.swing.JLabel();
        lblFlightTwoArrive = new javax.swing.JLabel();
        lblReceiptAirlineTypeTwo = new javax.swing.JLabel();
        lblDateOfDepartureTwo = new javax.swing.JLabel();
        lblDepartLocationTwo = new javax.swing.JLabel();
        lblArriveLocationTwo = new javax.swing.JLabel();
        lblArrivalDate = new javax.swing.JLabel();
        lblAirlineTypeFlightTwo = new javax.swing.JLabel();
        pnlGuests = new javax.swing.JPanel();
        pnlGuestsBar = new javax.swing.JPanel();
        lblGuests = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGuests = new javax.swing.JTextArea();
        lblDateOfTransaction = new javax.swing.JLabel();
        lblReceiptTransactionNumber = new javax.swing.JLabel();
        btnContinue = new javax.swing.JButton();
        lblAutoReceipt = new javax.swing.JLabel();
        pnlTopBar = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblTagLine = new javax.swing.JLabel();
        pnlIcon = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(654, 950));

        pnlReceiptBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlReceiptBackground.setToolTipText("");
        pnlReceiptBackground.setLayout(null);

        lblTransactionNumber.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblTransactionNumber.setForeground(new java.awt.Color(252, 177, 48));
        lblTransactionNumber.setText("Transaction Number:");
        pnlReceiptBackground.add(lblTransactionNumber);
        lblTransactionNumber.setBounds(40, 164, 119, 16);

        lblDate.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(252, 177, 48));
        lblDate.setText("Date:");
        pnlReceiptBackground.add(lblDate);
        lblDate.setBounds(428, 164, 30, 16);

        pnlFlightOne.setBackground(new java.awt.Color(255, 255, 255));
        pnlFlightOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 72, 134), 4));

        pnlFlighOneBar.setBackground(new java.awt.Color(29, 72, 134));

        lblFlightOne.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblFlightOne.setForeground(new java.awt.Color(252, 177, 48));
        lblFlightOne.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFlightOne.setText("Flight One");

        javax.swing.GroupLayout pnlFlighOneBarLayout = new javax.swing.GroupLayout(pnlFlighOneBar);
        pnlFlighOneBar.setLayout(pnlFlighOneBarLayout);
        pnlFlighOneBarLayout.setHorizontalGroup(
            pnlFlighOneBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlighOneBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFlightOne, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFlighOneBarLayout.setVerticalGroup(
            pnlFlighOneBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlighOneBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFlightOne)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFlightOneDepart.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFlightOneDepart.setForeground(new java.awt.Color(252, 177, 48));
        lblFlightOneDepart.setText("Depart:");

        lblFlightOneArrive.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFlightOneArrive.setForeground(new java.awt.Color(252, 177, 48));
        lblFlightOneArrive.setText("Arrive:");

        lblReceiptAirlineTypeOne.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblReceiptAirlineTypeOne.setForeground(new java.awt.Color(252, 177, 48));
        lblReceiptAirlineTypeOne.setText("Airline Type:");

        lblDateofDepartureOne.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblDateofDepartureOne.setForeground(new java.awt.Color(252, 177, 48));
        lblDateofDepartureOne.setText("Date of Departure:");

        lblDepartLocationOne.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblDepartLocationOne.setForeground(new java.awt.Color(252, 177, 48));
        lblDepartLocationOne.setText(Destination.cboOrigin.getSelectedItem().toString());

        lblArriveLocationOne.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblArriveLocationOne.setForeground(new java.awt.Color(252, 177, 48));
        lblArriveLocationOne.setText(Destination.cboDestination.getSelectedItem().toString());

        lblDepartureDate.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblDepartureDate.setForeground(new java.awt.Color(252, 177, 48));
        dateFormatter();
        lblDepartureDate.setText(flightOne);

        lblAirlineTypeFlightOne.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblAirlineTypeFlightOne.setForeground(new java.awt.Color(252, 177, 48));
        lblAirlineTypeFlightOne.setText(AirlineType.cboAirlineType.getSelectedItem().toString());

        javax.swing.GroupLayout pnlFlightOneLayout = new javax.swing.GroupLayout(pnlFlightOne);
        pnlFlightOne.setLayout(pnlFlightOneLayout);
        pnlFlightOneLayout.setHorizontalGroup(
            pnlFlightOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFlighOneBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFlightOneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlFlightOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblReceiptAirlineTypeOne)
                    .addComponent(lblFlightOneDepart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFlightOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepartLocationOne)
                    .addComponent(lblAirlineTypeFlightOne))
                .addGap(36, 36, 36)
                .addGroup(pnlFlightOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDateofDepartureOne)
                    .addComponent(lblFlightOneArrive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFlightOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArriveLocationOne)
                    .addComponent(lblDepartureDate))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlFlightOneLayout.setVerticalGroup(
            pnlFlightOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlightOneLayout.createSequentialGroup()
                .addComponent(pnlFlighOneBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlFlightOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlightOneDepart)
                    .addComponent(lblFlightOneArrive)
                    .addComponent(lblDepartLocationOne)
                    .addComponent(lblArriveLocationOne))
                .addGap(31, 31, 31)
                .addGroup(pnlFlightOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReceiptAirlineTypeOne)
                    .addComponent(lblDateofDepartureOne)
                    .addComponent(lblDepartureDate)
                    .addComponent(lblAirlineTypeFlightOne))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pnlReceiptBackground.add(pnlFlightOne);
        pnlFlightOne.setBounds(22, 202, 608, 204);

        pnlFlightTwo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFlightTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 72, 134), 4));
        if(Destination.cboOneWayRoundTrip.getSelectedItem().equals("One-Way")){
            pnlFlightTwo.setVisible(false);
        }

        pnlFlightTwoBar.setBackground(new java.awt.Color(29, 72, 134));

        lblFlightTwo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblFlightTwo.setForeground(new java.awt.Color(252, 177, 48));
        lblFlightTwo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFlightTwo.setText("Flight Two");

        javax.swing.GroupLayout pnlFlightTwoBarLayout = new javax.swing.GroupLayout(pnlFlightTwoBar);
        pnlFlightTwoBar.setLayout(pnlFlightTwoBarLayout);
        pnlFlightTwoBarLayout.setHorizontalGroup(
            pnlFlightTwoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlightTwoBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFlightTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFlightTwoBarLayout.setVerticalGroup(
            pnlFlightTwoBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlightTwoBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFlightTwo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFlightTwoDepart.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFlightTwoDepart.setForeground(new java.awt.Color(252, 177, 48));
        lblFlightTwoDepart.setText("Depart:");

        lblFlightTwoArrive.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFlightTwoArrive.setForeground(new java.awt.Color(252, 177, 48));
        lblFlightTwoArrive.setText("Arrive:");

        lblReceiptAirlineTypeTwo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblReceiptAirlineTypeTwo.setForeground(new java.awt.Color(252, 177, 48));
        lblReceiptAirlineTypeTwo.setText("Airline Type:");

        lblDateOfDepartureTwo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblDateOfDepartureTwo.setForeground(new java.awt.Color(252, 177, 48));
        lblDateOfDepartureTwo.setText("Date of Departure:");

        lblDepartLocationTwo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblDepartLocationTwo.setForeground(new java.awt.Color(252, 177, 48));
        lblDepartLocationTwo.setText(Destination.cboDestination.getSelectedItem().toString());

        lblArriveLocationTwo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblArriveLocationTwo.setForeground(new java.awt.Color(252, 177, 48));
        lblArriveLocationTwo.setText(Destination.cboOrigin.getSelectedItem().toString());

        lblArrivalDate.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblArrivalDate.setForeground(new java.awt.Color(252, 177, 48));
        dateFormatter();
        lblArrivalDate.setText(flightTwo);

        lblAirlineTypeFlightTwo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblAirlineTypeFlightTwo.setForeground(new java.awt.Color(252, 177, 48));
        lblAirlineTypeFlightTwo.setText(AirlineType.cboAirlineType.getSelectedItem().toString());

        javax.swing.GroupLayout pnlFlightTwoLayout = new javax.swing.GroupLayout(pnlFlightTwo);
        pnlFlightTwo.setLayout(pnlFlightTwoLayout);
        pnlFlightTwoLayout.setHorizontalGroup(
            pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFlightTwoBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFlightTwoLayout.createSequentialGroup()
                .addGroup(pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFlightTwoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblReceiptAirlineTypeTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAirlineTypeFlightTwo))
                    .addGroup(pnlFlightTwoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblFlightTwoDepart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDepartLocationTwo)))
                .addGap(1, 1, 1)
                .addGroup(pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFlightTwoLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblFlightTwoArrive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblArriveLocationTwo))
                    .addGroup(pnlFlightTwoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblDateOfDepartureTwo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblArrivalDate)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlFlightTwoLayout.setVerticalGroup(
            pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFlightTwoLayout.createSequentialGroup()
                .addComponent(pnlFlightTwoBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFlightTwoDepart)
                        .addComponent(lblDepartLocationTwo))
                    .addGroup(pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFlightTwoArrive)
                        .addComponent(lblArriveLocationTwo)))
                .addGap(18, 18, 18)
                .addGroup(pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFlightTwoLayout.createSequentialGroup()
                        .addGroup(pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReceiptAirlineTypeTwo)
                            .addComponent(lblAirlineTypeFlightTwo))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlFlightTwoLayout.createSequentialGroup()
                        .addGroup(pnlFlightTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDateOfDepartureTwo)
                            .addComponent(lblArrivalDate))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );

        pnlReceiptBackground.add(pnlFlightTwo);
        pnlFlightTwo.setBounds(22, 424, 608, 204);

        pnlGuests.setBackground(new java.awt.Color(255, 255, 255));
        pnlGuests.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 72, 134), 4));

        pnlGuestsBar.setBackground(new java.awt.Color(29, 72, 134));

        lblGuests.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblGuests.setForeground(new java.awt.Color(252, 177, 48));
        lblGuests.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGuests.setText("Guests");

        javax.swing.GroupLayout pnlGuestsBarLayout = new javax.swing.GroupLayout(pnlGuestsBar);
        pnlGuestsBar.setLayout(pnlGuestsBarLayout);
        pnlGuestsBarLayout.setHorizontalGroup(
            pnlGuestsBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuestsBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlGuestsBarLayout.setVerticalGroup(
            pnlGuestsBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuestsBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuests)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        guestsMethod();
        txtGuests.setEditable(false);
        txtGuests.setBackground(new java.awt.Color(255, 255, 255));
        txtGuests.setColumns(20);
        txtGuests.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtGuests.setForeground(new java.awt.Color(252, 177, 48));
        txtGuests.setRows(5);
        txtGuests.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtGuests.setEnabled(false);
        jScrollPane1.setViewportView(txtGuests);

        javax.swing.GroupLayout pnlGuestsLayout = new javax.swing.GroupLayout(pnlGuests);
        pnlGuests.setLayout(pnlGuestsLayout);
        pnlGuestsLayout.setHorizontalGroup(
            pnlGuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGuestsBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlGuestsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlGuestsLayout.setVerticalGroup(
            pnlGuestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGuestsLayout.createSequentialGroup()
                .addComponent(pnlGuestsBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlReceiptBackground.add(pnlGuests);
        pnlGuests.setBounds(22, 646, 608, 204);

        lblDateOfTransaction.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lblDateOfTransaction.setForeground(new java.awt.Color(252, 177, 48));
        lblDateOfTransaction.setText(CURRENT_DATE_FORMATTED);
        pnlReceiptBackground.add(lblDateOfTransaction);
        lblDateOfTransaction.setBounds(464, 152, 146, 32);

        lblReceiptTransactionNumber.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        lblReceiptTransactionNumber.setForeground(new java.awt.Color(252, 177, 48));
        lblReceiptTransactionNumber.setText(Transaction.txtTransactionNumber.getText());
        pnlReceiptBackground.add(lblReceiptTransactionNumber);
        lblReceiptTransactionNumber.setBounds(165, 152, 146, 32);

        btnContinue.setBackground(new java.awt.Color(29, 72, 134));
        btnContinue.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnContinue.setForeground(new java.awt.Color(252, 177, 48));
        btnContinue.setText("Continue>>");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        pnlReceiptBackground.add(btnContinue);
        btnContinue.setBounds(523, 877, 107, 27);

        lblAutoReceipt.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblAutoReceipt.setForeground(new java.awt.Color(252, 177, 48));
        lblAutoReceipt.setText("Airline Airlines Automated Receipt");
        pnlReceiptBackground.add(lblAutoReceipt);
        lblAutoReceipt.setBounds(20, 870, 222, 20);

        pnlTopBar.setBackground(new java.awt.Color(29, 72, 134));
        pnlTopBar.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(252, 177, 48));
        lblTitle.setText("AIRLINE AIRLINES");
        pnlTopBar.add(lblTitle);
        lblTitle.setBounds(197, 28, 301, 48);

        lblTagLine.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTagLine.setForeground(new java.awt.Color(252, 177, 48));
        lblTagLine.setText("SAMPLE TAGLINE HERE");
        pnlTopBar.add(lblTagLine);
        lblTagLine.setBounds(297, 82, 201, 25);

        pnlIcon.setBackground(new java.awt.Color(29, 72, 134));

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        String imagePath = "com" + File.separator + "iaapdevgroup2" + File.separator + "mercairlineticketing" + File.separator + "LogoWName.png";
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iaapdevgroup2/mercairlineticketing/resources/LogoWName.png"))); // NOI18N
        lblIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblIcon.setIconTextGap(0);
        int iconWidth = lblIcon.getIcon().getIconWidth();
        int iconHeight = lblIcon.getIcon().getIconHeight();
        lblIcon.setPreferredSize(new java.awt.Dimension(iconWidth, iconHeight));
        lblIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout pnlIconLayout = new javax.swing.GroupLayout(pnlIcon);
        pnlIcon.setLayout(pnlIconLayout);
        pnlIconLayout.setHorizontalGroup(
            pnlIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(pnlIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlIconLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlIconLayout.setVerticalGroup(
            pnlIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
            .addGroup(pnlIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlIconLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlTopBar.add(pnlIcon);
        pnlIcon.setBounds(510, 20, 112, 112);

        pnlReceiptBackground.add(pnlTopBar);
        pnlTopBar.setBounds(0, 0, 654, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReceiptBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlReceiptBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        int confirmation = JOptionPane.showConfirmDialog(null, "Do you want to close the program? Clicking no will put you back on the first window.", "Close", JOptionPane.YES_NO_OPTION);
        if(confirmation == 0){
            this.dispose();
        }
        else if(confirmation == 1){
            Destination d = new Destination();
            d.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnContinueActionPerformed
    
    private void dateFormatter(){
        switch(Destination.cboOneWayMM.getSelectedItem().toString()){
            case "Jan":
                flightOneMonth = 1;
                break;
            case "Feb":
                flightOneMonth = 2;
                break;
            case "Mar":
                flightOneMonth = 3;
                break;
            case "Apr":
                flightOneMonth = 4;
                break;
            case "May":
                flightOneMonth = 5;
                break;
            case "Jun":
                flightOneMonth = 6;
                break;
            case "Jul":
                flightOneMonth = 7;
                break;
            case "Aug":
                flightOneMonth = 8;
                break;
            case "Sept":
                flightOneMonth = 9;
                break;
            case "Oct":
                flightOneMonth = 10;
                break;
            case "Nov":
                flightOneMonth = 11;
                break;
            case "Dec":
                flightOneMonth = 12;
                break;
        }
        flightOneDay = Integer.parseInt(Destination.cboOneWayDD.getSelectedItem().toString());
        flightOneYear = Integer.parseInt(Destination.cboOneWayYear.getSelectedItem().toString());
        LocalDate flightOneDate = LocalDate.of(flightOneYear, flightOneMonth, flightOneDay);
        
        flightOneDay = flightOneDate.getDayOfMonth();
        flightOneMonth = flightOneDate.getMonthValue();
        flightOneYear = flightOneDate.getYear();
        
        flightOne = flightOneDate.format(dateFormatted);
        
        if(Destination.cboOneWayRoundTrip.getSelectedItem().equals("Round-Trip")){
            switch(Destination.cboRoundTripMM.getSelectedItem().toString()){
                case "Jan":
                    flightTwoMonth = 1;
                    break;
                case "Feb":
                    flightTwoMonth = 2;
                    break;
                case "Mar":
                    flightTwoMonth = 3;
                    break;
                case "Apr":
                    flightTwoMonth = 4;
                    break;
                case "May":
                    flightTwoMonth = 5;
                    break;
                case "Jun":
                    flightTwoMonth = 6;
                    break;
                case "Jul":
                    flightTwoMonth = 7;
                    break;
                case "Aug":
                    flightTwoMonth = 8;
                    break;
                case "Sept":
                    flightTwoMonth = 9;
                    break;
                case "Oct":
                    flightTwoMonth = 10;
                    break;
                case "Nov":
                    flightTwoMonth = 11;
                    break;
                case "Dec":
                    flightTwoMonth = 12;
                    break;
            }
            flightTwoDay = Integer.parseInt(Destination.cboRoundTripDD.getSelectedItem().toString());
            flightTwoYear = Integer.parseInt(Destination.cboRoundTripYear.getSelectedItem().toString());
            LocalDate flightTwoDate = LocalDate.of(flightTwoYear, flightTwoMonth, flightTwoDay);
            
            flightTwoDay = flightTwoDate.getDayOfMonth();
            flightTwoMonth = flightTwoDate.getMonthValue();
            flightTwoYear = flightTwoDate.getYear();
            
            flightTwo = flightTwoDate.format(dateFormatted);
        }
        else if(Destination.cboOneWayRoundTrip.getSelectedItem().equals("One-Way")){
            flightTwo = "a";
        }
    }
    
    private void guestsMethod(){
        int nameColumnIndex = 0;
        for(int a = 0; a < PriceBreakdown.passengerCount;a++){
            Object passengerNames = Passengers.table.getValueAt(a, nameColumnIndex);
            txtGuests.append(passengerNames.toString() + "\n");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAirlineTypeFlightOne;
    private javax.swing.JLabel lblAirlineTypeFlightTwo;
    private javax.swing.JLabel lblArrivalDate;
    private javax.swing.JLabel lblArriveLocationOne;
    private javax.swing.JLabel lblArriveLocationTwo;
    private javax.swing.JLabel lblAutoReceipt;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateOfDepartureTwo;
    private javax.swing.JLabel lblDateOfTransaction;
    private javax.swing.JLabel lblDateofDepartureOne;
    private javax.swing.JLabel lblDepartLocationOne;
    private javax.swing.JLabel lblDepartLocationTwo;
    private javax.swing.JLabel lblDepartureDate;
    private javax.swing.JLabel lblFlightOne;
    private javax.swing.JLabel lblFlightOneArrive;
    private javax.swing.JLabel lblFlightOneDepart;
    private javax.swing.JLabel lblFlightTwo;
    private javax.swing.JLabel lblFlightTwoArrive;
    private javax.swing.JLabel lblFlightTwoDepart;
    private javax.swing.JLabel lblGuests;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblReceiptAirlineTypeOne;
    private javax.swing.JLabel lblReceiptAirlineTypeTwo;
    private javax.swing.JLabel lblReceiptTransactionNumber;
    private javax.swing.JLabel lblTagLine;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTransactionNumber;
    private javax.swing.JPanel pnlFlighOneBar;
    private javax.swing.JPanel pnlFlightOne;
    private javax.swing.JPanel pnlFlightTwo;
    private javax.swing.JPanel pnlFlightTwoBar;
    private javax.swing.JPanel pnlGuests;
    private javax.swing.JPanel pnlGuestsBar;
    private javax.swing.JPanel pnlIcon;
    protected static javax.swing.JPanel pnlReceiptBackground;
    private javax.swing.JPanel pnlTopBar;
    private javax.swing.JTextArea txtGuests;
    // End of variables declaration//GEN-END:variables
}
